# Your Name or Company
title: Robert Felix Allen

# Description of your website. This is used for social sharing.
description: Personal website of Information Technology professional Robert Felix Allen.

# A brief blurb about yourself
content: I am an Information Technology operations and infrastructure professional based in the Boston metro area. Experienced in fast-paced startup culture with broad experience in Software-as-a-Service, Healthcare and Manufacturing. Connect today.

# Add your social links
social:
#  - platform: blog
#    url: https://blog.rfelixallen.com
  - platform: github
    url: https://github.com/rfelixallen
  - platform: linkedin
    url: https://linkedin.com/in/robert-felix-allen
  - platform: resume
    url: https://rfelixallen-card.s3.amazonaws.com/RobertFelixAllenResume.pdf

# General settings
# url: http://brianmaierjr.github.com/uni
# baseurl: "/uni" 
markdown: kramdown
sharing_image: share.jpg
google_analytics: "UA-89711625-1"

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: left
